exports.SUBADMIN_CREATE_SUCCESS = "Berhasil membuat subadmin"
exports.SUBADMIN_CREATE_FAIL = "Gagal membuat subadmin"
exports.SUBADMIN_DELETE_SUCCESS = "Berhasil menghapus subadmin"
exports.SUBADMIN_DELETE_FAIL = "Gagal menghapus subadmin"
exports.SUPERADMIN_CREATE_SUCCESS = "Berhasil membuat super admin"
exports.SUPERADMIN_CREATE_FAIL = "Gagal membuat super admin"
exports.SECRET_DOESNT_MATCH = "Secret key tidak sama"
exports.SUPERADMIN_ONLY_ONE = "Sudah ada 1 super admin"