exports.TIMELINE_NOT_FOUND = "Timeline tidak ditemukan"
exports.END_DATE_LT_START_DATE = "Tanggal selesai tidak boleh lebih kecil dari tanggal mulai"
exports.TIMELINE_ACTIVATE_SUCCESS = "Berhasil mengaktifkan timeline"
exports.TIMELINE_DISABLE_SUCCESS = "Berhasil menonaktifkan timeline"
exports.TIMELINE_DELETE_SUCCESS = "Berhasil menghapus timeline"
exports.ALL_TIMELINE_DISABLE = "Semua timeline dinonaktifkan"